---
- name: Unarchive Scala to /opt
  ansible.builtin.unarchive:
    src: "https://github.com/scala/scala3/releases/download/{{ scala_version }}/scala3-{{ scala_version }}.tar.gz"
    dest: /opt
    remote_src: yes
    creates: "/opt/scala3-{{ scala_version }}"
  tags: scala

- name: Create symlinks in /usr/local/bin
  ansible.builtin.file:
    src: "/opt/scala3-{{ scala_version }}/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - scala
    - scalac
    - scaladoc
  tags: scala
