---

- name: "Require Correct Linux Distribution"
  assert:
    that: (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('16.0.0', '>=')) or
          (ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('6.0.0', '>='))
    msg:  "This Linux distribution '{{ ansible_distribution }} {{ ansible_distribution_version }}' is not supported by the role."
  tags: [scala, sbt, java]

- name: "Include OS-Specific Variables"
  include_vars: "vars-{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
  tags: [scala, sbt, java]

- name: "Run OS-Specific Tasks"
  include: "tasks-{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
  tags: [scala, sbt, java]
