---

- set_fact:
    scala_package_url: "https://scala-lang.org/files/archive/scala-{{ scala_version }}.deb"
    ammonite_url:      "https://github.com/lihaoyi/Ammonite/releases/download/{{ ammonite_version }}/{{ scala_version | regex_replace('\\.\\d+$', '') }}-{{ ammonite_version }}"
  tags: scala

##  Java  ##

- name: "Add Java JDK Repository"
  apt_repository: repo="{{ java_jdk_repo }}" state=present validate_certs=no
  when: java_jdk_repo | default('') != ''
  tags: scala

- name: "Install Java JDK"
  apt: name="{{ java_jdk_package }}" state=latest
  when: java_jdk_package | default('') != ''
  tags: scala


##  SBT  ##

- name: "Add SBT Repository Key"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    state: present
  tags: scala

- name: "Add SBT Repository"
  apt_repository:
    state:          present
    repo:           deb https://dl.bintray.com/sbt/debian /
    validate_certs: no
  register: sbt_repo_added
  tags: scala

- name: "Install SBT"
  apt:
    name:         "{{ sbt_package }}"
    state:        present
    update_cache: "{% if sbt_repo_added | changed %}yes{% else %}no{% endif %}"
  when: sbt_package | default('') != ''
  tags: scala


##  Scala  ##

- name: "Install Scala"
  block:

  - name: "Download Scala Package"
    get_url:
      url: "{{ scala_package_url }}"
      dest: "/opt/scala-{{ scala_version }}.deb"
    register: scala_deb_package

  - name: "Install Scala Package"
    apt:
      deb: "/opt/scala-{{ scala_version }}.deb"
      state: present
    when: scala_deb_package | changed

  when: scala_version | default('') != ''
  tags: scala


##  Ammonite  ##

- name: "Download Ammonite"
  get_url:
    url:   "{{ ammonite_url }}"
    dest:  /usr/local/bin/amm
    owner: root
    group: root
    mode:  '0755'
  when: ammonite_version | default('') != ''
  tags: scala
