---

- set_fact:
    scala_package_url: "https://scala-lang.org/files/archive/scala-{{ scala_version }}.deb"
    ammonite_url:      "https://github.com/lihaoyi/Ammonite/releases/download/{{ ammonite_version }}/{{ scala_version | regex_replace('\\.\\d+$', '') }}-{{ ammonite_version }}"
  tags: scala

##  Java  ##

- name: "Add Java OpenJDK Repository Key"
  apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    state: present
  tags: scala

- name: "Add Java OpenJDK JDK Repository"
  apt_repository:
    state:          present
    repo:           "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ {{ distro_name }} main"
    validate_certs: no
    update_cache:   yes
  tags: scala

- name: "Install Java JDK"
  apt: name="{{ scala_java_package }}" state=latest
  tags: scala


##  SBT  ##

- name: "Install SBT"
  block:

   - name: "Add SBT Repository Key"
     apt_key:
       keyserver: keyserver.ubuntu.com
       id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
       state: present

   - name: "Add SBT Repository"
     apt_repository:
       state:          present
       repo:           deb https://dl.bintray.com/sbt/debian /
       validate_certs: no
       update_cache:   yes
     ignore_errors: true

   - name: "Install SBT"
     apt:
       name:  "{{ sbt_package }}"
       state: present

  when: sbt_package | default('') != ''
  tags: scala


##  Scala  ##

- name: "Install Scala"
  block:

  - name: "Download Scala Package"
    get_url:
      url: "{{ scala_package_url }}"
      dest: "/opt/scala-{{ scala_version }}.deb"
    register: scala_deb_package

  - name: "Install Scala Package"
    apt:
      deb: "/opt/scala-{{ scala_version }}.deb"
      state: present
    when: scala_deb_package | changed

  when: scala_version | default('') != ''
  tags: scala


##  Ammonite  ##

- name: "Download Ammonite"
  get_url:
    url:   "{{ ammonite_url }}"
    dest:  /usr/local/bin/amm
    owner: root
    group: root
    mode:  '0755'
  when: ammonite_version | default('') != ''
  tags: scala
