---

- name: "Install Java JDK"
  package: name="{{ scala_java_package }}" state=latest

- name: "Check if Scala Installed"
  yum: list=scala
  register: scala_pkg

- name: "Install Scala"
  yum: name="{{ scala_main_url }}" state=latest
  when: not scala_pkg.results[0].yumstate == 'installed'

- name: "Add SBT Repository"
  yum_repository:
    name: bintray-sbt-rpm
    enabled: yes
    description: Bintray SBT Repository
    baseurl: https://sbt.bintray.com/rpm
    gpgcheck: no
    repo_gpgcheck: no

- name: "Install SBT"
  yum: name="{{ scala_sbt_package }}" state=latest
